spring.application.name=auth-service
server.port=8081

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/skillhub_auth
spring.datasource.username=postgres
spring.datasource.password=Intel@321221
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
app.jwt.secret=dGhpcyBpcyBhIHZlcnkgbG9uZyBzZWNyZXQga2V5IGZvciBTa2lsbEh1YiBhcHBsaWNhdGlvbiB0aGF0IG11c3QgYmUgYXQgbGVhc3QgMjU2IGJpdHMgbG9uZw==
app.jwt.expiration-ms=86400000

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=false
eureka.instance.hostname=localhost
