spring.application.name=skill-service
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/skillhub_skills
spring.datasource.username=postgres
spring.datasource.password=Intel@321221
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.jwt.secret=dGhpcyBpcyBhIHZlcnkgbG9uZyBzZWNyZXQga2V5IGZvciBTa2lsbEh1YiBhcHBsaWNhdGlvbiB0aGF0IG11c3QgYmUgYXQgbGVhc3QgMjU2IGJpdHMgbG9uZw==

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=false
eureka.instance.hostname=localhost
